wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1669283885.660336
    t:
      1:
      - 1
      - 5
      - 41
      - 48
      - 53
      - 54
      - 55
      2:
      - 1
      - 5
      - 41
      - 48
      - 53
      - 54
      - 55
      3:
      - 16
      - 23
      4: 3.8.10
      5: 0.13.2
      8:
      - 6
augment:
  desc: null
  value: false
augment_prob:
  desc: null
  value: []
bs:
  desc: null
  value: 30
crop:
  desc: null
  value: cube_irl
model:
  desc: null
  value: resnet10
model_size:
  desc: null
  value: 6
n_epoch_class:
  desc: null
  value: 40
n_epoch_proj:
  desc: null
  value: 40
name_target:
  desc: null
  value: pm_post_tavi
normalization:
  desc: null
  value: global
oversample:
  desc: null
  value: true
patience:
  desc: null
  value: 15
size:
  desc: null
  value: 200
type_scan:
  desc: null
  value: systole
use_wandb:
  desc: null
  value: true
